// <auto-generated />
using BlossomInstitute.Infraestructure.DataBase;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace BlossomInstitute.Infraestructure.Migrations
{
    [DbContext(typeof(DataBaseService))]
    partial class AddCursoThemeIcon
    {
    }
}
